/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as MainPopularIndexRouteImport } from './routes/_main.popular.index'
import { Route as MainGenreIndexRouteImport } from './routes/_main.genre.index'
import { Route as MainSeriesComicIdIndexRouteImport } from './routes/_main.series.$comicId.index'
import { Route as MainReadComicIdChapterIdIndexRouteImport } from './routes/_main.read.$comicId.$chapterId.index'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainPopularIndexRoute = MainPopularIndexRouteImport.update({
  id: '/popular/',
  path: '/popular/',
  getParentRoute: () => MainRoute,
} as any)
const MainGenreIndexRoute = MainGenreIndexRouteImport.update({
  id: '/genre/',
  path: '/genre/',
  getParentRoute: () => MainRoute,
} as any)
const MainSeriesComicIdIndexRoute = MainSeriesComicIdIndexRouteImport.update({
  id: '/series/$comicId/',
  path: '/series/$comicId/',
  getParentRoute: () => MainRoute,
} as any)
const MainReadComicIdChapterIdIndexRoute =
  MainReadComicIdChapterIdIndexRouteImport.update({
    id: '/read/$comicId/$chapterId/',
    path: '/read/$comicId/$chapterId/',
    getParentRoute: () => MainRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/genre': typeof MainGenreIndexRoute
  '/popular': typeof MainPopularIndexRoute
  '/series/$comicId': typeof MainSeriesComicIdIndexRoute
  '/read/$comicId/$chapterId': typeof MainReadComicIdChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/genre': typeof MainGenreIndexRoute
  '/popular': typeof MainPopularIndexRoute
  '/series/$comicId': typeof MainSeriesComicIdIndexRoute
  '/read/$comicId/$chapterId': typeof MainReadComicIdChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_main/genre/': typeof MainGenreIndexRoute
  '/_main/popular/': typeof MainPopularIndexRoute
  '/_main/series/$comicId/': typeof MainSeriesComicIdIndexRoute
  '/_main/read/$comicId/$chapterId/': typeof MainReadComicIdChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/genre'
    | '/popular'
    | '/series/$comicId'
    | '/read/$comicId/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/genre'
    | '/popular'
    | '/series/$comicId'
    | '/read/$comicId/$chapterId'
  id:
    | '__root__'
    | '/_main'
    | '/_main/'
    | '/_main/genre/'
    | '/_main/popular/'
    | '/_main/series/$comicId/'
    | '/_main/read/$comicId/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/popular/': {
      id: '/_main/popular/'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof MainPopularIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/genre/': {
      id: '/_main/genre/'
      path: '/genre'
      fullPath: '/genre'
      preLoaderRoute: typeof MainGenreIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/series/$comicId/': {
      id: '/_main/series/$comicId/'
      path: '/series/$comicId'
      fullPath: '/series/$comicId'
      preLoaderRoute: typeof MainSeriesComicIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/read/$comicId/$chapterId/': {
      id: '/_main/read/$comicId/$chapterId/'
      path: '/read/$comicId/$chapterId'
      fullPath: '/read/$comicId/$chapterId'
      preLoaderRoute: typeof MainReadComicIdChapterIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainGenreIndexRoute: typeof MainGenreIndexRoute
  MainPopularIndexRoute: typeof MainPopularIndexRoute
  MainSeriesComicIdIndexRoute: typeof MainSeriesComicIdIndexRoute
  MainReadComicIdChapterIdIndexRoute: typeof MainReadComicIdChapterIdIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainGenreIndexRoute: MainGenreIndexRoute,
  MainPopularIndexRoute: MainPopularIndexRoute,
  MainSeriesComicIdIndexRoute: MainSeriesComicIdIndexRoute,
  MainReadComicIdChapterIdIndexRoute: MainReadComicIdChapterIdIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
