/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as MainPopularIndexRouteImport } from './routes/_main.popular.index'
import { Route as MainSeriesComicIdIndexRouteImport } from './routes/_main.series.$comicId.index'
import { Route as MainReadChapterIdIndexRouteImport } from './routes/_main.read.$chapterId.index'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainPopularIndexRoute = MainPopularIndexRouteImport.update({
  id: '/popular/',
  path: '/popular/',
  getParentRoute: () => MainRoute,
} as any)
const MainSeriesComicIdIndexRoute = MainSeriesComicIdIndexRouteImport.update({
  id: '/series/$comicId/',
  path: '/series/$comicId/',
  getParentRoute: () => MainRoute,
} as any)
const MainReadChapterIdIndexRoute = MainReadChapterIdIndexRouteImport.update({
  id: '/read/$chapterId/',
  path: '/read/$chapterId/',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/popular': typeof MainPopularIndexRoute
  '/read/$chapterId': typeof MainReadChapterIdIndexRoute
  '/series/$comicId': typeof MainSeriesComicIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/popular': typeof MainPopularIndexRoute
  '/read/$chapterId': typeof MainReadChapterIdIndexRoute
  '/series/$comicId': typeof MainSeriesComicIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_main/popular/': typeof MainPopularIndexRoute
  '/_main/read/$chapterId/': typeof MainReadChapterIdIndexRoute
  '/_main/series/$comicId/': typeof MainSeriesComicIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/popular' | '/read/$chapterId' | '/series/$comicId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/popular' | '/read/$chapterId' | '/series/$comicId'
  id:
    | '__root__'
    | '/_main'
    | '/_main/'
    | '/_main/popular/'
    | '/_main/read/$chapterId/'
    | '/_main/series/$comicId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/popular/': {
      id: '/_main/popular/'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof MainPopularIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/series/$comicId/': {
      id: '/_main/series/$comicId/'
      path: '/series/$comicId'
      fullPath: '/series/$comicId'
      preLoaderRoute: typeof MainSeriesComicIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/read/$chapterId/': {
      id: '/_main/read/$chapterId/'
      path: '/read/$chapterId'
      fullPath: '/read/$chapterId'
      preLoaderRoute: typeof MainReadChapterIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainPopularIndexRoute: typeof MainPopularIndexRoute
  MainReadChapterIdIndexRoute: typeof MainReadChapterIdIndexRoute
  MainSeriesComicIdIndexRoute: typeof MainSeriesComicIdIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainPopularIndexRoute: MainPopularIndexRoute,
  MainReadChapterIdIndexRoute: MainReadChapterIdIndexRoute,
  MainSeriesComicIdIndexRoute: MainSeriesComicIdIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
