/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as MainUpdateIndexRouteImport } from './routes/_main.update.index'
import { Route as MainSearchIndexRouteImport } from './routes/_main.search.index'
import { Route as MainPopularIndexRouteImport } from './routes/_main.popular.index'
import { Route as MainGenreIndexRouteImport } from './routes/_main.genre.index'
import { Route as ReadComicIdChapterIdIndexRouteImport } from './routes/read.$comicId.$chapterId.index'
import { Route as MainSeriesComicIdIndexRouteImport } from './routes/_main.series.$comicId.index'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainUpdateIndexRoute = MainUpdateIndexRouteImport.update({
  id: '/update/',
  path: '/update/',
  getParentRoute: () => MainRoute,
} as any)
const MainSearchIndexRoute = MainSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => MainRoute,
} as any)
const MainPopularIndexRoute = MainPopularIndexRouteImport.update({
  id: '/popular/',
  path: '/popular/',
  getParentRoute: () => MainRoute,
} as any)
const MainGenreIndexRoute = MainGenreIndexRouteImport.update({
  id: '/genre/',
  path: '/genre/',
  getParentRoute: () => MainRoute,
} as any)
const ReadComicIdChapterIdIndexRoute =
  ReadComicIdChapterIdIndexRouteImport.update({
    id: '/read/$comicId/$chapterId/',
    path: '/read/$comicId/$chapterId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MainSeriesComicIdIndexRoute = MainSeriesComicIdIndexRouteImport.update({
  id: '/series/$comicId/',
  path: '/series/$comicId/',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/genre': typeof MainGenreIndexRoute
  '/popular': typeof MainPopularIndexRoute
  '/search': typeof MainSearchIndexRoute
  '/update': typeof MainUpdateIndexRoute
  '/series/$comicId': typeof MainSeriesComicIdIndexRoute
  '/read/$comicId/$chapterId': typeof ReadComicIdChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/genre': typeof MainGenreIndexRoute
  '/popular': typeof MainPopularIndexRoute
  '/search': typeof MainSearchIndexRoute
  '/update': typeof MainUpdateIndexRoute
  '/series/$comicId': typeof MainSeriesComicIdIndexRoute
  '/read/$comicId/$chapterId': typeof ReadComicIdChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_main/genre/': typeof MainGenreIndexRoute
  '/_main/popular/': typeof MainPopularIndexRoute
  '/_main/search/': typeof MainSearchIndexRoute
  '/_main/update/': typeof MainUpdateIndexRoute
  '/_main/series/$comicId/': typeof MainSeriesComicIdIndexRoute
  '/read/$comicId/$chapterId/': typeof ReadComicIdChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/genre'
    | '/popular'
    | '/search'
    | '/update'
    | '/series/$comicId'
    | '/read/$comicId/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/genre'
    | '/popular'
    | '/search'
    | '/update'
    | '/series/$comicId'
    | '/read/$comicId/$chapterId'
  id:
    | '__root__'
    | '/_main'
    | '/_main/'
    | '/_main/genre/'
    | '/_main/popular/'
    | '/_main/search/'
    | '/_main/update/'
    | '/_main/series/$comicId/'
    | '/read/$comicId/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  ReadComicIdChapterIdIndexRoute: typeof ReadComicIdChapterIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/update/': {
      id: '/_main/update/'
      path: '/update'
      fullPath: '/update'
      preLoaderRoute: typeof MainUpdateIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/search/': {
      id: '/_main/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MainSearchIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/popular/': {
      id: '/_main/popular/'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof MainPopularIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/genre/': {
      id: '/_main/genre/'
      path: '/genre'
      fullPath: '/genre'
      preLoaderRoute: typeof MainGenreIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/read/$comicId/$chapterId/': {
      id: '/read/$comicId/$chapterId/'
      path: '/read/$comicId/$chapterId'
      fullPath: '/read/$comicId/$chapterId'
      preLoaderRoute: typeof ReadComicIdChapterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/series/$comicId/': {
      id: '/_main/series/$comicId/'
      path: '/series/$comicId'
      fullPath: '/series/$comicId'
      preLoaderRoute: typeof MainSeriesComicIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainGenreIndexRoute: typeof MainGenreIndexRoute
  MainPopularIndexRoute: typeof MainPopularIndexRoute
  MainSearchIndexRoute: typeof MainSearchIndexRoute
  MainUpdateIndexRoute: typeof MainUpdateIndexRoute
  MainSeriesComicIdIndexRoute: typeof MainSeriesComicIdIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainGenreIndexRoute: MainGenreIndexRoute,
  MainPopularIndexRoute: MainPopularIndexRoute,
  MainSearchIndexRoute: MainSearchIndexRoute,
  MainUpdateIndexRoute: MainUpdateIndexRoute,
  MainSeriesComicIdIndexRoute: MainSeriesComicIdIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  ReadComicIdChapterIdIndexRoute: ReadComicIdChapterIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
